src/routes/billing.py
import datetime

from flask import Blueprint, render_template, url_for, redirect, flash, request

from src.authentication import admin_login
from src.database.models.payments import Payment
from src.database.models.subscriptions import Subscriptions, SubscriptionDetails
from src.database.models.users import User
from src.logger import init_logger
from src.main import subscriptions_controller, paypal_controller

billing_route = Blueprint('billing', __name__)
billing_logger = init_logger('billing_logger')


@billing_route.get('/admin/billing')
@admin_login
async def get_billing(user: User):
    """

    :param user:
    :return:
    """

    subscription: Subscriptions = await subscriptions_controller.get_company_subscription(company_id=user.company_id)
    if not subscription:
        subscription = {}
    billing_logger.info(f"{subscription}")
    plan_details: SubscriptionDetails = await subscriptions_controller.return_plan_details(plan_name=subscription.plan_name)
    context = dict(user=user, subscription_account=subscription, plan_details=plan_details)
    return render_template('billing/billing.html', **context)

@billing_route.get('/admin/billing/tax-invoice/<string:transaction_id>')
@admin_login
async def print_subscription_payment_tax_invoice(user: User, transaction_id: str):
    """

        print_subscription_payment_tax_invoice
    """
    payment: Payment = await subscriptions_controller.get_company_subscription_payment(transaction_id=transaction_id)
    if not isinstance(payment, Payment):
        message="Unable to find the invoice"
        flash(message=message,category="danger")
        return redirect(url_for('billing.get_billing'))

    subscription_account: Subscriptions = await subscriptions_controller.get_company_subscription(company_id=user.company_id)
    if subscription_account.subscription_id != payment.subscription_id:
        message="You changed your subscription since making this payment can no longer reprint your invoice"
        flash(message=message,category="danger")
        return redirect(url_for('billing.get_billing'))

    generated_on = datetime.datetime.now()
    context = dict(user=user, subscription_account=subscription_account, payment=payment, generated_on=generated_on)

    if payment.package_id:
        package = await subscriptions_controller.get_package(package_id=payment.package_id)
        context.update(package=package)

    return render_template('receipts/system/subscription_payment.html', **context)

@billing_route.post('/admin/billing/paynow')
@admin_login
async def do_pay_now(user: User):
    """
        this will pay the monthly payment as stipulated on billing
    :param user:
    :return:
    """
    # company_detail: Company = await company_controller.get_company_details(company_id=user.company_id)
    subscription: Subscriptions = await subscriptions_controller.get_company_subscription(company_id=user.company_id)

    success_url: str = url_for('billing.payment_successful', _external=True, _scheme='https')
    failure_url: str = url_for('billing.payment_failure', _external=True, _scheme='https')

    payment, is_created = await paypal_controller.create_payment(payment_details=subscription,
                                                                 user=user,
                                                                 success_url=success_url, failure_url=failure_url)
    if is_created:
        # Redirect user to PayPal for payment approval
        for link in payment.links:
            if link.method == "REDIRECT":
                return redirect(link.href)
    else:
        flash(message=f"Error creating Payment : {payment.error}", category="danger")
        return redirect(url_for('company.get_admin'))


@billing_route.get('/admin/billing/payment-successfull')
@admin_login
async def payment_successful(user: User):
    """

    :param user:
    :return:
    """
    _payload = request.json
    _signature = request.headers.get('Paypal-Transmission-Sig', None)
    if not _signature:
        return redirect(url_for('home.get_home'))

    request_valid = await paypal_controller.verify_signature(payload=_payload, signature=_signature)
    if not request_valid:
        return redirect(url_for('home.get_home'))

    data = request.json

    amount = int(_payload.get("resource", {}).get("amount", {}).get("total"))
    subscription = await subscriptions_controller.get_company_subscription(company_id=user.company_id)

    payment = Payment(subscription_id=subscription.subscription_id,
                      amount_paid=amount,
                      payment_method="paypal",
                      is_successful=True, month=1)

    payment = await subscriptions_controller.add_company_payment(payment=payment)
    billing_logger.info("subscription payment succeeded")
    billing_logger.info(payment)
    if amount < subscription.subscription_amount:
        flash(message=f"you have paid : {amount} instead of {subscription.subscription_amount}", category="danger")

    else:
        flash(message=f"Payment Of {amount} Made Successfully", category="success")

    return redirect(url_for('company.get_admin'))


@billing_route.get('/admin/billing/payment-failed')
@admin_login
async def payment_failure(user: User):
    """

    :param user:
    :return:
    """
    message: str = "Payment was not successful please try again later"
    billing_logger.error(message)

    flash(message=message, category="danger")
    return redirect(url_for('company.get_admin'))

src/routes/subscriptions.py
import json
from typing import Dict
from flask import Blueprint, url_for, flash, redirect, request, render_template, jsonify
from pydantic import ValidationError
from src.authentication import admin_login
from src.database.models.companies import Company
from src.database.models.payments import Payment
from src.database.models.subscriptions import PlanNames, SubscriptionDetails, Subscriptions, TopUpPacks, Package
from src.database.models.users import User
from src.logger import init_logger
from src.main import company_controller, paypal_controller, subscriptions_controller, payfast_controller

subscriptions_route = Blueprint('subscriptions', __name__)

subscription_logger = init_logger(name="subscriptions_route_logger")


@subscriptions_route.post('/_ipn/payfast')
async def payfast_ipn():
    # Convert the incoming form data to a dictionary
    payfast_dict_data: Dict[str, str] = request.form.to_dict()
    subscription_logger.info(f"Incoming Payment Notification: {payfast_dict_data}")

    # Validate the received data
    if await payfast_controller.is_valid_payfast_data(payfast_dict_data=payfast_dict_data):
        # Extracting relevant fields from the data
        payment_status = payfast_dict_data.get('payment_status')
        amount_gross = payfast_dict_data.get('amount_gross')
        pf_payment_id = payfast_dict_data.get('pf_payment_id')
        item_name = payfast_dict_data.get('item_name')
        email_address = payfast_dict_data.get('email_address')
        merchant_id = payfast_dict_data.get('merchant_id')
        # TODO - send payment receipt and notice welcoming the client to our services
        # Parsing the item_name to get plan_name and payment_type
        plan_name, payment_type = item_name.split(" ")

        # Custom fields which might not be present
        subscription_id = payfast_dict_data.get("custom_str1")
        company_id = payfast_dict_data.get("custom_str2")
        uid = payfast_dict_data.get("custom_str3")
        subscription_logger.info(f"Verified Request Data For ITN of company: {company_id} ")

        if payment_status == "COMPLETE" and payment_type.casefold() == "subscription":
            # Fetch the subscription details based on company_id
            subscription = await subscriptions_controller.get_company_subscription(company_id=company_id)
            subscription_logger.info(f"Able to Retrive the Company Subsciption: {subscription}")
            if isinstance(subscription, Subscriptions):
                # Create a Payment record for the subscription
                try:
                    payment = Payment(
                        subscription_id=subscription.subscription_id,
                        amount_paid=amount_gross,
                        payment_method="payfast",
                        is_successful=True,
                        month=1,  # Assuming the payment covers 1 month, adjust if needed
                        comments=f"payfast payment for company : {company_id}"
                    )
                    subscription_logger.info(f"Created Payment Type : {payment}")

                    # Store the payment in the database
                    payment_data: Payment = await subscriptions_controller.add_company_payment(payment=payment)
                    subscription_logger.info(f"Payment Record Created: {payment_data}")
                    # Return a success response
                    return jsonify(
                        dict(message=f"Successfully paid for {plan_name} subscription", data=payfast_dict_data)), 200
                except ValidationError as e:
                    subscription_logger.warning(str(e))

            else:
                subscription_logger.warning(f"Could not Verify if subscription is of the type Subscrtiption")

            subscription_logger.warning(f"Payment not complete or not a subscription: {payfast_dict_data}")
            return jsonify(dict(message="Payment not complete or invalid payment type", data=payfast_dict_data)), 400

        else:
            # Log the issue or handle failed payment status
            subscription_logger.warning(f"Payment not complete or not a subscription: {payfast_dict_data}")
            return jsonify(dict(message="Payment not complete or invalid payment type", data=payfast_dict_data)), 400
    else:
        # Handle invalid data, possibly log and alert
        subscription_logger.warning(f"Invalid PayFast data received: {payfast_dict_data}")
        return jsonify(dict(message="Invalid data received", data=payfast_dict_data)), 400


@subscriptions_route.get('/subscriptions/payfast-success')
@admin_login
async def payfast_payment_complete(user: User):
    """
    payfast_payment_complete
        guru
        :param user:
        :return:
    """
    flash(message="Payment completed successfully", category="success")
    return redirect(url_for('company.get_admin'))


@subscriptions_route.get('/subscriptions/payfast-failure')
@admin_login
async def payfast_payment_failed(user: User):
    """

    :param user:
    :return:
    """
    flash(message="Payment was cancelled please try again later", category="danger")
    return redirect(url_for('company.get_admin'))


@subscriptions_route.get('/subscriptions/subscriptions')
@admin_login
async def get_subscriptions(user: User):
    """
        **get_subscriptions**
    :param user:
    :return:
    """
    if not user.company_id:
        message: str = "You cannot subscribe please ensure to create a company"
        flash(message=message, category="danger")
        subscription_logger.info(message)
        return redirect(url_for('home.get_home'))

    subscription_account: Subscriptions = await subscriptions_controller.get_company_subscription(
        company_id=user.company_id)
    subscription_plans: list[SubscriptionDetails] = await subscriptions_controller.return_all_plan_details()
    context = dict(user=user, subscription_account=subscription_account, subscription_plans=subscription_plans)
    return render_template('billing/subscriptions.html', **context)


async def paypal_payment(subscription_details: Subscriptions, user: User):
    """

    :return:
    """
    success_url: str = url_for('subscriptions.subscription_payment_successful', _external=True, _scheme='https')
    failure_url: str = url_for('subscriptions.subscription_payment_failure', _external=True, _scheme='https')
    payment, is_created = await paypal_controller.create_payment(payment_details=subscription_details, user=user,
                                                                 success_url=success_url, failure_url=failure_url)
    if is_created:
        # Redirect user to PayPal for payment approval
        for link in payment.links:
            if link.method == "REDIRECT":
                return redirect(link.href)
    else:
        flash(message=f"Error creating Payment : {payment.error}", category="danger")
        return redirect(url_for('company.get_admin'))


async def make_direct_deposit(subscription_details: Subscriptions, user: User):
    """

    :param subscription_details:
    :param user:
    :return:
    """

    context = dict(user=user, subscription_details=subscription_details)
    return render_template('billing/direct_deposit.html', **context)


@subscriptions_route.post('/subscriptions/payment-method')
@admin_login
async def payment_method_selected(user: User):
    """

    :param user:
    :return:
    """
    payment_method = request.form.get('payment_method')
    subscription_id: str = request.form.get('subscription_id')
    subscription_details: Subscriptions = await subscriptions_controller.get_company_subscription(
        company_id=user.company_id)

    if subscription_details.subscription_id != subscription_id:
        flash(message="there was a problem making payment for this subscription", category="danger")
        return redirect(url_for('subscriptions.get_subscriptions'))
    if payment_method == "paypal":
        return await paypal_payment(subscription_details=subscription_details, user=user)
    elif payment_method == "payfast":
        return await payfast_controller.payfast_subscription_payment(subscription_details=subscription_details,
                                                                     user=user)
    elif payment_method == "direct_deposit":
        return await make_direct_deposit(subscription_details=subscription_details, user=user)
    print(f"Payment Method: {payment_method}")


@subscriptions_route.post('/subscriptions/subscribe/<string:option>')
@admin_login
async def do_subscribe(user: User, option: str):
    """

    :param option:
    :param user:
    :return:
    """

    if option not in PlanNames.plan_names():
        message: str = "Please select a valid subscription plan"
        flash(message=message, category="danger")
        subscription_logger.info(message)
        return redirect(url_for('company.get_admin'))

    company_detail: Company = await company_controller.get_company_details(company_id=user.company_id)

    subscription_details: SubscriptionDetails = SubscriptionDetails().create_plan(plan_name=option.upper())
    subscription_logger.info(f"Created plan details: {subscription_details}")

    subscription = Subscriptions(**subscription_details.dict(), company_id=company_detail.company_id, payments=[])
    await subscriptions_controller.add_update_company_subscription(subscription=subscription)
    flash(message=f"you have successfully created a {subscription.plan_name} Account", category="success")
    return redirect(url_for('subscriptions.get_subscriptions'))


@subscriptions_route.get('/subscriptions/payment/success')
@admin_login
async def subscription_payment_successful(user: User):
    try:
        # Load JSON data

templates/billing/billing.html
{% extends "layouts/page.html" %}
{% block content %}
<section id="main-content">
    <div class="card shadow-sm border-info">
        <div class="card-header">
            <h3 class="card-title">
                <span class="font-weight-bold text-info">
                    <i class="fa fa-money"> </i>
                    Billing
                </span>
            </h3>
        </div>
        <div class="card-body">
            {% if subscription_account %}
                <ul class="list-group">
                    <div class="card-header">
                        <h3 class="card-title font-weight-bold text-success"> Subscription Details</h3>
                    </div>
                    <li class="list-group-item">
                        <span class="font-weight-bold">
                            Subscribed Plan : <span class="text-info pull-right">{{ plan_details.plan_name|title }}</span>
                        </span>
                    </li>

                    <li class="list-group-item">
                        <span class="font-weight-bold">
                            Total Clients: <span class="text-info pull-right">{{ plan_details.total_clients| number }} Policy Holders</span>
                        </span>
                    </li>
                    <li class="list-group-item">
                        <span class="font-weight-bold">
                            Total SMS: <span class="text-info pull-right">{{ plan_details.total_sms| number }} SMS/Month</span>
                        </span>
                    </li>
                    <li class="list-group-item">
                        <span class="font-weight-bold">
                            Total Emails: <span class="text-info pull-right">{{ plan_details.total_emails| number }} Emails/Month </span>
                        </span>
                    </li>

                    <div class="card-header">
                        <h3 class="card-title font-weight-bold text-success">Payment Details</h3>
                    </div>

                    <li class="list-group-item">
                        <span class="font-weight-bold">
                            Date Registered: <span class="text-info pull-right">{{ subscription_account.date_subscribed if subscription_account.date_subscribed else 'N/A' }}</span>
                        </span>
                    </li>
                    <li class="list-group-item">
                        <span class="font-weight-bold">
                            Monthly Payment Amount: <span class="text-success pull-right">R {{ subscription_account.subscription_amount| number }}.00</span>
                        </span>
                    </li>
                </ul>
                    <div class="card  shadow-sm border-primary">
                    <div class="card-header">
                        <h3 class="card-title font-weight-bold text-success">
                            <i class="fa fa-money"> </i>
                            Payments
                        </h3>
                    </div>
                        <div class="card-body">
                                {% if subscription_account and  subscription_account.payments %}
                                    <h4 class="mt-4">Payments</h4>
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th class="font-weight-bold text-info">Date</th>
                                                <th class="font-weight-bold text-info">Amount</th>
                                                <th class="font-weight-bold text-info">Status</th>
                                                <th class="font-weight-bold text-info">Print</th>
                                                <th class="font-weight-bold text-info"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for payment in subscription_account.payments %}
                                                <tr>
                                                    <td>{{ payment.date_paid.strftime('%Y-%m-%d') }}</td>
                                                    <td>R {{ payment.amount_paid| number }}.00</td>
                                                    <td>
                                                        {% if payment.is_successful %}
                                                            <span class="badge badge-success">Sucess</span>
                                                        {% else %}
                                                            <span class="badge badge-danger">Failed</span>
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        <a href="{{ url_for('billing.print_subscription_payment_tax_invoice', transaction_id=payment.transaction_id) }}" class="btn btn-sm btn-rounded btn-outline-info">
                                                        <i class="fa fa-print"> </i>
                                                        Invoice
                                                        </a>
                                                    </td>
                                                    <td></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <div class="card-header">
                                            <h3 class="card-title font-italic text-danger align-content-center">No payments recorded.</h3>
                                    </div>

                                {% endif %}
                            </div>
                        </div>
                        {% if subscription_account and not subscription_account.is_paid_for_current_month %}
                                <div class="card card-columns shadow-lg border-primary">
                                    <button  class="btn btn-lg btn-outline-info btn-rounded btn-block"
                                    data-toggle="modal" data-target="#paymentMethodsModal"
                                    >
                                        PAY NOW
                                    </button>

                                </div>
                        {% endif %}
            {% else %}
                <p>No subscription data available.</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}


{% include "admin/managers/subscriptions/payment_methods.html" %}

templates/billing/direct_deposit.html

{% extends "layouts/page.html" %}
{% block content %}
    <section id="main-content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title text-info">
                    <i class="fa fa-user-circle"> </i>
                    Account
                </h3>
                <span class="card-title font-weight-light text-info">Direct Deposit Payments</span>
            </div>
            <div class="card-body">

                <ul class="list-group">
                    <li class="list-group-item">Bank Name: Capitec </li>
                    <li class="list-group-item">Account Number: </li>
                    <li class="list-group-item">Account Holder: </li>
                    <li class="list-group-item">Account Type: </li>
                    <li class="list-group-item">Reference : <span class="pull-right badge badge-info">{{ subscription_details.reference }}</span></li>
                    <li class="list-group-item">Payment Amount : <span class="pull-right badge badge-success">R {{ subscription_details.subscription_amount|number }}.00</span></li>
                </ul>
            </div>
            <div class="card-footer">
                <span class="font-weight-bold text-danger">Once payment has been made your account will be credited</span>
            </div>
        </div>
    </section>
{% endblock %}

templates/billing/subscriptions.html
{% extends "layouts/page.html" %}
{% block content %}
    <section id="main-content">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title text-info">
                    <i class="fa fa-user-circle"> </i>
                    Subscribe
                </h3>
                <span class="card-title font-weight-light text-info">In order to activate your account select a subscription option, Subscribe then Make Payment</span>
            </div>
            {% if subscription_account %}
                {% include "admin/managers/subscriptions/account.html" %}
            {% else %}
                {% include "admin/managers/subscriptions/plans_description.html" %}
            {% endif %}
        </div>
    </section>
{% endblock %}



