src/database/models/support.py
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

from src.utils import create_id


class TicketStatus(str, Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    CLOSED = "closed"

    @classmethod
    def UN_RESOLVED(cls) -> list[str]:
        return [cls.OPEN.value, cls.IN_PROGRESS.value]


class TicketTypes(str, Enum):
    BILLING = "billing"
    COVERS = "covers"
    MESSAGING = "messaging"
    EMPLOYEES = "employees"
    PLANS = "plans"

    @classmethod
    def ticket_types_list(cls) -> list[str]:
        return [cls.BILLING.value, cls.COVERS.value, cls.MESSAGING.value, cls.EMPLOYEES.value, cls.PLANS.value]


class TicketPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"

    @classmethod
    def priority_list(cls) -> list[str]:
        """

        :return:
        """
        return [cls.LOW.value, cls.MEDIUM.value, cls.HIGH.value, cls.URGENT.value]


def create_ticket_id() -> str:
    return create_id()


class TicketMessage(BaseModel):
    message_id: str = Field(default_factory=create_id)
    ticket_id: str
    sender_id: str
    message: str
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Ticket(BaseModel):
    ticket_id: str

    user_id: str

    assigned_to: str | None = Field(default=None)
    ticket_type: str
    subject: str

    status: str = Field(default=TicketStatus.OPEN.value)
    priority: str = Field(default=TicketPriority.MEDIUM.value)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    messages: list[TicketMessage]

    @property
    def sorted_messages(self):
        return sorted(self.messages, key=lambda msg: msg.created_at) if self.messages else []


class NewTicketForm(BaseModel):
    ticket_type: str
    subject: str
    priority: str
    message: str

src/routes/support.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pydantic import ValidationError

from src.authentication import user_details, login_required, admin_login
from src.database.models.support import TicketPriority, TicketTypes, NewTicketForm, Ticket, TicketMessage, \
    create_ticket_id, TicketStatus
from src.database.models.users import User
from src.logger import init_logger
from src.main import support_controller

support_route = Blueprint('support', __name__)
support_logger = init_logger("support_logger")


async def create_ticket(new_ticket: NewTicketForm, user: User) -> tuple[Ticket, TicketMessage]:
    ticket_id = create_ticket_id()
    ticket_message: TicketMessage = TicketMessage(message=new_ticket.message, sender_id=user.uid,
                                                  ticket_id=ticket_id)
    messages = [ticket_message]
    ticket = Ticket(**new_ticket.dict(), messages=messages, ticket_id=ticket_id, user_id=user.uid)
    return ticket, ticket_message


@support_route.get('/support')
@login_required
async def get_support(user: User):
    """

    :param user:
    :return:
    """

    context: dict[str, dict[any, any] | str | list[str]] = dict(user=user) if user and user.email else dict()

    ticket_priority_list = TicketPriority.priority_list()
    ticket_types_list = TicketTypes.ticket_types_list()
    previous_tickets = await support_controller.get_user_support_tickets(uid=user.uid)
    context.update(ticket_priority_list=ticket_priority_list,
                   ticket_types_list=ticket_types_list,
                   previous_tickets=previous_tickets)

    return render_template('support/support.html', **context)


@support_route.get('/support/ticket/<string:ticket_id>')
@login_required
async def view_ticket(user: User, ticket_id: str):
    """

    :param user:
    :param ticket_id:
    :return:
    """
    context: dict[str, dict[any, any] | str | list[str]] = dict(user=user) if user and user.email else dict()
    support_ticket: Ticket = await support_controller.get_support_ticket_by_ticket_id(ticket_id=ticket_id)
    support_logger.info(f"Support Ticket : {support_ticket}")
    uid_email_tags: dict[str, str] = await support_controller.get_uid_tags(support_ticket=support_ticket)
    context.update(support_ticket=support_ticket.dict(), uid_email_tags=uid_email_tags)

    return render_template('support/view_ticket.html', **context)


@support_route.post('/support/ticket-create')
@login_required
async def do_create_ticket(user: User):
    """

    :param user:
    :return:
    """
    try:
        new_ticket = NewTicketForm(**request.form)
    except ValidationError as e:
        support_logger.error(str(e))
        flash(message="Please fill in all the details to create ticket", category="danger")
        return redirect(url_for('support.get_support'))

    ticket, ticket_message = await create_ticket(new_ticket, user)

    ticket: Ticket = await support_controller.create_support_ticket(ticket=ticket)
    ticket_message: TicketMessage = await support_controller.add_ticket_message(ticket_message=ticket_message)
    message = "Successfully created ticket"
    ticket_id = f"Ticket ID : {ticket.ticket_id}"
    flash(message=message, category="success")
    flash(message=ticket_id, category="success")
    return redirect(url_for('support.get_support'))


@support_route.post('/support/ticket-response/<string:ticket_id>')
@login_required
async def respond_to_ticket(user: User, ticket_id: str):
    """

    :param user:
    :param ticket_id:
    :return:
    """
    message: str = request.form.get('message')
    new_message: TicketMessage = TicketMessage(ticket_id=ticket_id, sender_id=user.uid, message=message)
    ticket_message: TicketMessage = await support_controller.add_ticket_message(ticket_message=new_message)
    await support_controller.ticket_set_status(ticket_id=ticket_id, status=TicketStatus.IN_PROGRESS.value)

    flash(message="response successfully sent", category="danger")
    return redirect(url_for('support.get_support'))


@support_route.post('/support/ticket-resolve/<string:ticket_id>')
@login_required
async def resolve_ticket(user: User, ticket_id: str):
    """

    :param user:
    :param ticket_id:
    :return:
    """
    await support_controller.ticket_set_status(ticket_id=ticket_id, status=TicketStatus.RESOLVED.value)

    flash(message="Ticket Status Successfully changed to resolved", category="danger")
    return redirect(url_for('support.view_ticket', ticket_id=ticket_id))


@support_route.post('/support/ticket-close/<string:ticket_id>')
@login_required
async def close_ticket(user: User, ticket_id: str):
    """
        **close_ticket**

    :param user:
    :param ticket_id:
    :return:
    """
    await support_controller.ticket_set_status(ticket_id=ticket_id, status=TicketStatus.CLOSED.value)

    flash(message="Ticket Successfully Closed", category="danger")
    return redirect(url_for('support.view_ticket', ticket_id=ticket_id))


# Admin Section
@support_route.get('/admin/support/unresolved')
@admin_login
async def admin_unresolved_support_tickets(user: User):
    """

    :param user:
    :return:
    """
    unresolved_tickets: list[Ticket] = await support_controller.load_unresolved_tickets()
    context = dict(user=user, unresolved_tickets=unresolved_tickets)
    return render_template('support/admin/support.html', **context)


templates/support/support.html
{% extends "layouts/page.html" %}

{% block content %}

<section id="main-content">
    <div class="card shadow-lg border-warning">
        <div class="card-header">
            <h2 class="card-title font-weight-bold text-info">
                <i class="fa fa-ticket"></i>
                Support Tickets
            </h2>
        </div>
        <div class="card-body">
            <!-- Tab Navigation -->
            <ul class="nav nav-tabs" id="ticketTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="progress-tab" data-toggle="tab" href="#progress" role="tab" aria-controls="progress" aria-selected="false">
                        <span class="font-weight-bold text-info">
                            <i class="fa fa-ticket"> </i>
                            My Tickets
                        </span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" id="create-tab" data-toggle="tab" href="#create" role="tab" aria-controls="create" aria-selected="true">

                        <span class="font-weight-bold text-info">
                            <i class="fa fa-ticket"> </i>
                            Create Ticket
                        </span>
                    </a>
                </li>
            </ul>

            <!-- Tab Content -->
            <div class="tab-content" id="ticketTabContent">
                <!-- Create Ticket Tab -->
                <div class="tab-pane fade" id="create" role="tabpanel" aria-labelledby="create-tab">
                    <form class="form-horizontal mt-4" action="{{ url_for('support.do_create_ticket') }}" method="post">
                        <div class="form-group">
                            <label for="ticket_type" class="font-weight-light text-info">Ticket Type</label>
                            <div class="form-control-feedback">
                                <select class="form-control form-control-lg" name="ticket_type" id="ticket_type">
                                    <option value="" disabled selected>Select Ticket Type</option>
                                    {% for ticket_type in ticket_types_list %}
                                        <option value="{{ ticket_type }}">{{ ticket_type| title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="subject" class="font-weight-light text-info">Subject</label>
                            <div class="form-control-feedback">
                                <input type="text" class="form-control form-control-lg" name="subject" id="subject">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="message" class="font-weight-light text-info">Message</label>
                            <div class="form-control-feedback">
                                <textarea class="form-control form-control-lg" name="message" id="message"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="priority" class="font-weight-light text-info">Ticket Priority</label>
                            <div class="form-control-feedback">

                                <select id="priority" name="priority" class="form-control form-control-lg">
                                    <option value="" selected disabled>Select Priority</option>
                                    {% for priority in ticket_priority_list %}
                                        <option value="{{ priority }}">{{ priority|title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-lg btn-block btn-outline-success">
                                <i class="fa fa-ticket"></i>
                                Submit Ticket
                            </button>
                        </div>
                    </form>
                </div>

                <!-- Previous Tickets Tab -->
                <div class="tab-pane fade show active" id="progress" role="tabpanel" aria-labelledby="progress-tab">
                    <div class="mt-4">

                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
{#                                        <th scope="col">Ticket ID</th>#}
                                        <th scope="col">Subject</th>
                                        <th scope="col">Date Created</th>
                                        <th scope="col">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for ticket in previous_tickets %}
                                        <tr>
{#                                            <td class="font-weight-bold">{{ ticket.ticket_id }}</td>#}
                                            <td  class="font-weight-light">
                                                <a class="font-weight-light" href="{{ url_for('support.view_ticket', ticket_id=ticket.ticket_id) }}">
                                                    <span class="text-info">
                                                        <i class="fa fa-info-circle"> </i>
                                                    </span>

                                                    <span class="font-weight-light badge badge-info text-white font-weight-bold">
                                                        {{ ticket.subject }}
                                                    </span>
                                                </a>

                                            </td>
                                            <td>
                                                <span class="font-weight-bold">
                                                    {{ ticket.created_at }}
                                                </span>
                                            </td>
                                            <td>
                                                {% if ticket.status == 'open' %}
                                                    <span class="badge badge-success">Open</span>
                                                {% elif ticket.status == 'in_progress' %}
                                                    <span class="badge badge-warning">In Progress</span>
                                                {% elif ticket.status == 'resolved' %}
                                                    <span class="badge badge-primary">Resolved</span>
                                                {% elif ticket.status == 'closed' %}
                                                    <span class="badge badge-secondary">Closed</span>
                                                {% else %}
                                                    <span class="badge badge-light">Unknown</span>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/support/view_ticket.html
{% extends "layouts/page.html" %}

{% block content %}

<section id="main-content">
    <div class="card shadow-lg border-warning">
        <div class="card-header">
            <h2 class="card-title font-weight-bold text-info">
                <i class="fa fa-ticket"></i>
                View Ticket
            </h2>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-md-6">
                    <h5 class="font-weight-bold">Ticket Details</h5>
                <ul class="list-group">
                    <li class="list-group-item"> <span class="text-info font-weight-light">Category: </span> <span class="font-weight-bold pull-right text-right">{{ support_ticket.ticket_type | title }}</span></li>
                    <li class="list-group-item"> <span class="text-info font-weight-light">Priority: </span> <span class="font-weight-bold pull-right">{{ support_ticket.priority | title}}</span></li>
                    <li class="list-group-item"> <span class="text-info font-weight-light">Subject:</span> <span class="font-weight-bold pull-right">{{ support_ticket.subject | title }}</span></li>
                    <li class="list-group-item m-t-6">
                        <span class="font-italic">Status:</span>
                        {% if support_ticket.status == 'open' %}
                            <span class="badge badge-success pull-right">Open</span>
                        {% elif support_ticket.status == 'in_progress' %}
                            <span class="badge badge-warning pull-right">In Progress</span>
                        {% elif support_ticket.status == 'resolved' %}
                            <span class="badge badge-primary pull-right">Resolved</span>
                        {% elif support_ticket.status == 'closed' %}
                            <span class="badge badge-secondary pull-right">Closed</span>
                        {% else %}
                            <span class="badge badge-light pull-right">Unknown</span>
                        {% endif %}
                    </li>
                    <li class="list-group-item"> <span class="text-success">Created At:</span> <span class="pull-right">{{ support_ticket.created_at }}</span></li>
                    <li class="list-group-item"> <span class="text-warning">Updated At:</span> <span class="pull-right">{{ support_ticket.updated_at }}</span></li>
                    <li class="list-group-item">
                        <form class="form-horizontal"
                              action="{{ url_for('support.resolve_ticket', ticket_id=support_ticket.ticket_id) }}"
                              method="POST"
                        >

                            <button type="submit" class="btn btn-block btn-outline-success btn-sm btn-rounded">
                                <span class="font-weight-bold">
                                    <i class="fa fa-info"></i>
                                        Is Issue Resolved ?
                                </span>
                            </button>
                        </form>
                    </li>

                </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h5 class="font-weight-bold">Messages</h5>
                    <div class="list-group">
                        {% for message in support_ticket.sorted_messages %}
                            <div class="list-group-item list-group-item-action">

                                <div class="d-flex w-100 justify-content-between m-t-9">
                                    <span class="mb-1"> <span class="text-success">from:</span> <span class="text-info">{{ uid_email_tags.get(message.sender_id) }}</span></span>
                                    <small>{{ message.created_at }}</small>
                                </div>
                                <div class="border-info">
                                    <span class="mb-1">{{ message.message }}</span>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                 <div class="col-md-12">
                     <h5 class="font-weight-bold">Response</h5>
                     <form class="form-horizontal" method="POST" action="{{ url_for('support.respond_to_ticket', ticket_id=support_ticket.ticket_id) }}">
                         <div class="form-group">
                             <label for="message">Message</label>
                             <textarea id="message" name="message" class="form-control-lg form-control"></textarea>
                         </div>

                            <button type="submit"
                                    class="btn btn-block btn-outline-primary btn-rounded btn-sm"
                            >
                                <span class="font-weight-bold">
                                    <i class="fa fa-send"> </i>
                                    Respond
                                </span>
                            </button>

                     </form>

                <form class="form-horizontal m-t-9"
                      action="{{ url_for('support.close_ticket', ticket_id=support_ticket.ticket_id) }}"
                      method="POST">

                        <button type="submit"
                                class="btn btn-block btn-outline-danger btn-rounded btn-sm"
                        >
                        <span class="font-weight-bold">
                            <i class="fa fa-power-off"> </i>
                            Close Ticket
                        </span>
                        </button>

                </form>

                 </div>


            </div>

        </div>
    </div>
</section>

{% endblock %}