src/routes/documents.py
import os
from flask import Blueprint
from flask import send_from_directory, abort, url_for, redirect, flash

from src.database.models.covers import Claims
from src.main import covers_controller
from src.database.models.users import User
from src.authentication import login_required
from src.logger import init_logger
from src.utils import claims_folder_path

documents_route = Blueprint('documents', __name__)
documents_logger = init_logger('documents_logger')


@documents_route.get('/documents/<string:company_id>/<string:claim_number>/<string:filename>')
@login_required
async def download_claims_documents(user: User, company_id: str, claim_number: str, filename: str):
    """
        allows employess to download claims documents
    :param user:
    :param company_id:
    :param claim_number:
    :param filename:
    :return:
    """
    file_path = claims_folder_path(company_id=company_id, claim_number=claim_number)
    claim_data: Claims = await covers_controller.get_claim_data(claim_number=claim_number)

    documents_logger.info(f"Company ID for User: {user.company_id}")
    if user.company_id != claim_data.company_id:
        flash(message="You are not authorized to download this claim file")
        return redirect(url_for('admin.get_admin'))

    # Check if the file exists
    if not os.path.exists(os.path.join(file_path, filename )):
        return abort(404)  # Return a 404 if the file does not exist

    # Serve the file
    return send_from_directory(directory=file_path, path=filename)

templates/claims/claim_form.html
{% extends "layouts/page.html" %}
{% block content %}
    <section id="main-content">
        <div class="card shadow-lg border-info">
            <div class="card-header bg-facebook">
                <h3 class="card-title text-white">
                    <i class="fa fa-user-circle"></i>
                    Funeral Policy Claim Form
                </h3>
                <span class="card-title font-weight-light text-white">
                    Log new claims or obtain the status of a claim using this form
                </span>
            </div>
            <div class="card-body m-t-12">

                <form id="retrieve-policy-form" action="{{ url_for('covers.retrieve_policy') }}" method="POST">
                    <div class="form-group">
                        <label for="policy_number" class="font-weight-bold">Policy Number:</label>
                        <input type="text" id="policy_number" name="policy_number" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="policy_holder_id_number" class="font-weight-bold">Policy Holder ID Number:</label>
                        <input type="text" id="id_number" name="id_number" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Start Claim Processing</button>
                    </div>
                </form>

            </div>
        </div>
    </section>
{% endblock %}

templates/claims/claim_status.html
{% extends "layouts/page.html" %}
{% block content %}
    <section id="main-content">
        <div class="container mt-4">
            <!-- Claim Data Card -->
            <div class="card shadow-lg border-info mb-4">
                <div class="card-header bg-facebook">
                    <h3 class="card-title text-white">
                        <i class="fa fa-folder"></i>
                        {{ company_details.company_name|title }}
                    </h3>

                </div>
                {% if company_details %}

                    <div class="alert alert-info">
                        <ul class="list-group">
                            <li class="list-group-item font-weight-bold text-info">Claims Department</li>
                            <li class="list-group-item font-weight-bold">Contact Person: <span class="pull-right">{{ employee_details.display_names|title }}</span></li>
                            <li class="list-group-item font-weight-bold">Cell: <span class="pull-right">{{ employee_details.contact_number }}</span></li>
                        </ul>
                    </div>
                {% endif %}

                {% if claim_data and client_data %}
                    <div class="alert alert-info">
                        <ul class="list-group">
                            <li class="list-group-item font-weight-bold">FUNERAL COVER CLAIM Of : <span class="pull-right badge badge-success text-white">{{ client_data.client_display_name }}</span></li>
                            <li class="list-group-item">ID Number: <span class="pull-right">{{ client_data.id_number }}</span></li>
                            <li class="list-group-item m-t-4">DOB: <span class="pull-right">{{ client_data.date_of_birth }}</span></li>
                            <li class="list-group-item">Nationality: <span class="pull-right">{{ client_data.nationality }}</span></li>
                        </ul>
                    </div>
                {% endif %}

                {% if claim_data %}
                    <div class="alert alert-info">
                        <ul class="list-group">
                            <li class="list-group-item font-weight-bold">
                                Claim Number:
                                <span class="pull-right badge badge-success text-white">{{ claim_data.claim_number }}</span>
                            </li>
                            <li class="list-group-item m-t-4">
                                Policy Number:
                                <span class="pull-right">{{ claim_data.policy_number }}</span>
                            </li>
                            <li class="list-group-item">
                                Plan Number:
                                <span class="pull-right">{{ claim_data.plan_number }}</span>
                            </li>

                            <li class="list-group-item">
                                Claim Amount / (Value of Services):
                                <span class="pull-right">R {{ claim_data.claim_amount| number }}.00 </span>
                            </li>
                            <li class="list-group-item">
                                Claim Total Paid / (Valued of Services to be Rendered):
                                <span class="pull-right">R {{ claim_data.claim_total_paid| number }}.00</span>
                            </li>
                            <li class="list-group-item">
                                (Expected) Date of Service:
                                <span class="pull-right">{{ claim_data.date_of_service.strftime('%Y-%m-%d') if claim_data.date_of_service else 'N/A' }}</span>
                            </li>
                            <li class="list-group-item">
                                Date Claim Logged:
                                <span class="pull-right">{{ claim_data.date_claim_logged.strftime('%Y-%m-%d') }}</span>
                            </li>
                            <li class="list-group-item">
                                Claim Type:
                                <span class="pull-right">{{ claim_data.claim_type }}</span>
                            </li>
                            <li class="list-group-item">
                                Claim Status:
                                <span class="pull-right badge
                                    {% if claim_data.claim_status == 'Rejected' %}
                                        badge-danger
                                    {% elif claim_data.claim_status == 'Approved' %}
                                        badge-success
                                    {% elif claim_data.claim_status == 'Completed' %}
                                        badge-primary
                                    {% elif claim_data.claim_status == 'In Progress' %}
                                        badge-warning
                                    {% else %}
                                        badge-secondary
                                    {% endif %}">
                                    {{ claim_data.claim_status }}
                                </span>
                            </li>
                            <li class="list-group-item">
                                Notes:
                                <span class="pull-right">{{ claim_data.notes if claim_data.notes else 'N/A' }}</span>
                            </li>
                        </ul>
                    </div>
                {% endif %}

                    <!-- Display Loaded Data -->
                    {% if claim_data and claimant_data %}
                        <div class="alert alert-info">
                            <ul class="list-group">
                                <li class="list-group-item font-weight-bold">Personal Details of the Responsible Person <span class="text-info">(Family Liaison)</span> </li>
                                <li class="list-group-item m-t-4">Names: <span class="pull-right">{{ claimant_data.display_name }}</span></li>
                                <li class="list-group-item">ID Number: <span class="pull-right">{{ claimant_data.id_number }}</span></li>
                                <li class="list-group-item m-t-4">Cell: <span class="pull-right">{{ claimant_data.cell }}</span></li>
                                <li class="list-group-item">Alternate Cell: <span class="pull-right">{{ claimant_data.alt_cell }}</span></li>
                                <li class="list-group-item">Email: <span class="pull-right">{{ claimant_data.email }}</span></li>
                                <li class="list-group-item m-t-8">Relationship to Deceased: <span class="pull-right badge badge-info text-white font-weight-bold">{{ claimant_data.relationship_to_deceased }}</span></li>
                            </ul>
                        </div>
                    {% endif %}

                    {% if bank_account %}
                        <div class="alert alert-info">
                            <ul class="list-group">
                                <li class="list-group-item font-weight-bold">Account Holder: <span class="pull-right badge badge-success text-white">{{ bank_account.display_account_holder }}</span></li>
                                <li class="list-group-item m-t-4">Bank Name <span class="pull-right">{{ bank_account.bank_name }}</span></li>
                                <li class="list-group-item">Account Number: <span class="pull-right">{{ bank_account.account_number }}</span></li>
                                <li class="list-group-item">Account Type: <span class="pull-right">{{ bank_account.account_type|title }}</span></li>
                            </ul>
                        </div>
                    {% endif %}

                    {% if claim_files %}
                        <div class="alert alert-info">
                            <h5>Supporting Documents:</h5>
                            <ul class="list-group">
                                {% for file in claim_files %}
                                    <li class="list-group-item"><a
                                            class="text-success font-weight-bold"
                                            href="{{ url_for('documents.download_claims_documents',
                                            company_id=claim_data.company_id,
                                            claim_number=claim_data.claim_number,
                                            filename=file) }}" target="_blank">
                                        <i class="ti-file"> </i>
                                        {{ file }}
                                    </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

            </div>
        </div>
    </section>
{% endblock %}

templates/claims/logged_claims.html
{% extends "layouts/page.html" %}
{% block content %}
    <section id="main-content">
        <div class="container mt-4">
            <!-- Claims Table Card -->
            <div class="card shadow-lg border-info mb-4">
                <div class="card-header bg-facebook">
                    <h3 class="card-title text-white">
                        <i class="fa fa-clipboard-list"></i>
                        logged Claims
                    </h3>
                </div>
                <div class="card-body">
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Select</th>
                                    <th>Claim Number</th>
                                    <th>Policy Number</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for claim in claims %}
                                    <tr>
                                        <td>
                                            <a href="{{ url_for('covers.retrieve_claim_status', claim_number=claim.claim_number) }}" class="btn btn-sm btn-outline-info btn-rounded">
                                                <i class="fa fa-link"></i>
                                                Open
                                            </a>
                                        </td>
                                        <td> <span class="font-weight-bold">{{ claim.claim_number }}</span></td>
                                        <td> <span class="font-weight-bold">{{ claim.policy_number }}</span></td>
                                        <td>
                                            <span class="badge
                                                {% if claim.claim_status == 'Rejected' %}
                                                    badge-danger
                                                {% elif claim.claim_status == 'Approved' %}
                                                    badge-success
                                                {% elif claim.claim_status == 'Completed' %}
                                                    badge-primary
                                                {% elif claim.claim_status == 'In Progress' %}
                                                    badge-warning
                                                {% else %}
                                                    badge-secondary
                                                {% endif %}">
                                                {{ claim.claim_status }}
                                            </span>
                                        </td>
                                        <td></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}